# Include this in your configuration.yaml (changing username, password, code & coutry).
# Remember to mark all your controls (remotes and keys) to be tracked, in order to 
# ensure synchronization between this alarm_control_panel and real securitas alarm

securitas_direct:
  username: your_securitas_username
  password: your_securitas_password
  installation: your_securitas_installation
  code: 1234
  country: ES
  lang: es

# remove '#' to enable debug for this component (to see logs: 'tail -f homeassistant.log') 
#logger:
#  logs:
#    custom_components.securitas_direct: debug
